name: code-style

on:
    push:
    pull_request:

permissions: write-all

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Checking PHP Syntax
                run: vendor/bin/pint --test
    
